#include "config\config.hpp"
#include "loadoutDialog\class_loadouts_config.hpp" 
#include "teleportDialog\teleportconfig.hpp"
#include "InsertionDialog\insertionConfig.hpp"
#include "timeDialog\timeConfig.hpp" 
#include "artilleryDialog\artilleryDialogConfig.hpp" 

#include "loadoutDialog\LoadoutDialog.hpp" 
#include "teleportDialog\TeleportDialog.hpp"
#include "InsertionDialog\InsertionDialog.hpp" 
#include "timeDialog\timeDialog.hpp"
#include "artilleryDialog\artilleryDialog.hpp"
#include "doorkeypad\doorkeypad.hpp"